### ISSUE TITLE
Build error: no exported member

### ISSUE THREAD

**Issue by rkedia145** [Bella-DeFinTech/uniswap-v3-bot#1]
Hi Bella Team, 

I'm trying to build this project (I ran 'tsc'), and I'm getting the following error: 

```
src/EventDBManager.ts:4:10 - error TS2305: Module '"uniswap-v3-simulator"' has no exported member 'DateConverter'.

4 import { DateConverter, JSBIDeserializer } from "uniswap-v3-simulator";
           ~~~~~~~~~~~~~

src/EventDBManager.ts:4:25 - error TS2305: Module '"uniswap-v3-simulator"' has no exported member 'JSBIDeserializer'.

4 import { DateConverter, JSBIDeserializer } from "uniswap-v3-simulator";
                          ~~~~~~~~~~~~~~~~

test/Backtest.test.ts:4:3 - error TS2305: Module '"uniswap-v3-simulator"' has no exported member 'TickMath'.

4   TickMath,
    ~~~~~~~~

test/Backtest.test.ts:5:3 - error TS2305: Module '"uniswap-v3-simulator"' has no exported member 'LiquidityMath'.

5   LiquidityMath,
    ~~~~~~~~~~~~~

test/Backtest.test.ts:6:3 - error TS2305: Module '"uniswap-v3-simulator"' has no exported member 'FullMath'.

6   FullMath,
    ~~~~~~~~

test/LogDBManager.ts:2:10 - error TS2305: Module '"uniswap-v3-simulator"' has no exported member 'DateConverter'.

2 import { DateConverter } from "uniswap-v3-simulator";
           ~~~~~~~~~~~~~


Found 6 errors.
```

I can get around this for now by manually copying over these files, but if there is a better way to resolve this please let me know! Since uniswap-v3-simulator is a npm package I don't think i need to add a reference to the other project in ts-config...

**Comment by neptune-v** [comment]
@rkedia145 Sorry for the late reply, we haven't been actively looking at this repo. 
But to your question, at the time you were trying it out, we hadn't finalized the package publishing, sorry for the inconvenience.
You might be on a problematic branch, things are now cleaned up and we are working on publishing a new release on npm now.

**Comment by neptune-v** [comment]
@rkedia145 We have published the npm package: https://www.npmjs.com/package/@bella-defintech/uniswap-v3-simulator

**Comment by rkedia145** [comment]
@neptune-v fantastic, thank you! I've gotten by importing the files locally, but i'll transition to the new package.
